[workspace]
members = [
    "crates/taskbook-common",
    "crates/taskbook-client",
    "crates/taskbook-server",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
